In [ ]:
import pandas as pd
from process_data_part1 import

ModuleNotFoundError: No module named 'workstreamB'

In [3]:
df= pd.read_csv("C:\\Users\\eyasf\\OneDrive\\Desktop\\projet_raies\\Data\\Output_data_workstreamB.csv")

In [6]:
# New data for workstream C
data1 = df.dropna(subset=["Spread_lag"]).copy()
data1 = data1.sort_values("Date").reset_index(drop=True)

data1["spread"] = data1["Spread_lag"]
data1.head()

,Date,USD_IB,Fixing_USD,Fixing_lag,Spread_same,Spread_lag,Spread_lag1,Spread_lag2,Spread_lag3,Spread_lag4,spread
0,2020-04-13,2.8924,2.89680,2.90640,-0.00440,-0.01400,NaN,NaN,NaN,NaN,-0.01400
1,2020-04-14,2.8894,2.88910,2.89680,0.00030,-0.00740,-0.0140,NaN,NaN,NaN,-0.00740
2,2020-04-15,2.8874,2.89520,2.88910,-0.00780,-0.00170,-0.0074,-0.0140,NaN,NaN,-0.00170
3,2020-04-16,2.9006,2.90135,2.89520,-0.00075,0.00540,-0.0017,-0.0074,-0.0140,NaN,0.00540
4,2020-04-17,2.9114,2.90870,2.90135,0.00270,0.01005,0.0054,-0.0017,-0.0074,-0.014,0.01005

In [9]:
data1.drop(columns=["Spread_same", "Spread_lag", "Spread_lag1", "Spread_lag2", "Spread_lag3", "Spread_lag4"], inplace=True, errors="ignore")
data1.head()

         Date  USD_IB  Fixing_USD  Fixing_lag   spread
0  2020-04-13  2.8924     2.89680     2.90640 -0.01400
1  2020-04-14  2.8894     2.88910     2.89680 -0.00740
2  2020-04-15  2.8874     2.89520     2.88910 -0.00170
3  2020-04-16  2.9006     2.90135     2.89520  0.00540
4  2020-04-17  2.9114     2.90870     2.90135  0.01005

In [14]:
# Transform the regim 0 -> normal marker and 1 -> stress marker
import numpy as np
probs_clean = probs.reset_index(drop=True)

data1 = data1.iloc[-len(probs_clean):].copy().reset_index(drop=True)

data1["P_regime_0"] = probs_clean[0]
data1["P_regime_1"] = probs_clean[1]

data1["regime"] = np.where(data1["P_regime_1"] > data1["P_regime_0"], 1, 0)

data1.head()

NameError: name 'probs' is not defined